import Head from 'next/head'
import Navbar from '@/components/organisms/Navbar'
import About from '@/components/organisms/About'
import Jumbotron from '@/components/organisms/Jumbotron'
import Project from '@/components/organisms/Project'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='container mx-auto'>
                <Navbar />
                <Jumbotron />
                <hr />
                <About />
                <hr />
                <Project />
            </div>
        </>
    )
}

export async function getServerSideProps() {
    return {
        props: {}, // will be passed to the page component as props
    }
}
